#!/usr/bin/env python

import argparse
import getpass
from pysqlcipher3 import dbapi2 as sqlcipher
import shutil
import sys
import tempfile
import zipfile

parser = argparse.ArgumentParser(description='Export transactions of a Sparkasse+ backup file to Subsembly SUPA format.')
parser.add_argument('-a', '--account', dest='account', default='%', help='Only export records of account IBAN', metavar='IBAN')
parser.add_argument('-p', '--password', dest='password', help='Password for opening the backup file', metavar='PASSWORD')
parser.add_argument('file', help='Sparkasse+ backup file to be converted', metavar='FILE')
args = parser.parse_args()

if args.password is None:
    args.password = getpass.getpass()

with zipfile.ZipFile(args.file, 'r') as zf:
    with zf.open([n for n in zf.namelist() if n.endswith('data.db')][0]) as datadb:
        with tempfile.NamedTemporaryFile() as dbfile:
            shutil.copyfileobj(datadb, dbfile)
            with sqlcipher.connect(dbfile.name) as db:
                db.execute("pragma key='%s'" % args.password.replace("'", "''"))
                db.execute("update konten set bic=bic || 'XXX' where bic like '________'")
                cursor = db.execute("""
                                    select
                                    u._id as Id,
                                    k.kontoWaehrung as OwnrAcctCcy,
                                    k.iban as OwnrAcctIBAN,
                                    k.kontoNummer as OwnrAcctNo,
                                    k.bic as OwnrAcctBIC,
                                    k.kontoBlz as OwnrAcctBankCode,
                                    u.buchungsDatum as BookgDt,
                                    u.valuta as ValDt,
                                    ltrim(replace(replace(u.betrag,'.',''),',','.'),'-') as Amt,
                                    u.waehrung as AmtCcy,
                                    case
                                        when instr(u.betrag,'-')=1 then
                                            'DBIT'
                                        else
                                            'CRDT'
                                        end as CdtDbtInd,
                                    u.endToEndReferenz as EndToEndId,
                                    u.kundenReferenz as PmtInfId,
                                    u.mandatsReferenz as MndtId,
                                    u.glaeubigerId as CdtrId,
                                    replace(replace(u.vwz,'\r',''),'\n',' ') as RmtInf,
                                    case
                                        when u.origin='CAMT' then
                                            u.camtAddInformation
                                        else
                                            u.buchungstext
                                        end as BookgTxt,
                                    u.primanota as PrimaNotaNo,
                                    u.reference as BankRef,
                                    u.swiftCode as BkTxCd,
                                    case
                                        when u.origin='CAMT' then
                                            case
                                                when (u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic) or
                                                     (u.remitterAccountNumber=k.kontoNummer and u.remitterBankcode=k.kontoBlz) then
                                                    u.payee
                                                else
                                                    case
                                                        when (u.payeeAccountNumber=k.iban and substr(u.payeeBankcode||'XXX',1,11)=k.bic) or
                                                             (u.payeeAccountNumber=k.kontoNummer and u.payeeBankcode=k.kontoBlz) then
                                                            u.remitter
                                                        else
                                                            case
                                                                when instr(u.betrag,'-')=1 then
                                                                    u.payee
                                                                else
                                                                    u.remitter
                                                                end
                                                        end
                                                end
                                        else
                                            u.name
                                        end as RmtdNm,
                                    null as RmtdAcctCtry,
                                    case
                                        when u.origin='CAMT' then
                                            case
                                                when (u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic) or
                                                     (u.payeeAccountNumber=k.iban and substr(u.payeeBankcode||'XXX',1,11)=k.bic) then
                                                    case
                                                        when u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic then
                                                            u.payeeAccountNumber
                                                        else
                                                            u.remitterAccountNumber
                                                        end
                                                else
                                                    null
                                                end
                                        else
                                            null
                                        end as RmtdAcctIBAN,
                                    case
                                        when u.origin='CAMT' then
                                            case
                                                when (u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic) or
                                                     (u.payeeAccountNumber=k.iban and substr(u.payeeBankcode||'XXX',1,11)=k.bic) then
                                                    null
                                                else
                                                    case
                                                        when u.remitterAccountNumber=k.kontoNummer and u.remitterBankcode=k.kontoBlz then
                                                            u.payeeAccountNumber
                                                        else
                                                            case
                                                                when u.payeeAccountNumber=k.kontoNummer and u.payeeBankcode=k.kontoBlz then
                                                                    u.remitterAccountNumber
                                                                else
                                                                    case
                                                                        when instr(u.betrag,'-')=1 then
                                                                            u.payeeAccountNumber
                                                                        else
                                                                            u.remitterAccountNumber
                                                                        end
                                                                end
                                                        end
                                                end
                                        else
                                            u.nummer
                                        end as RmtdAcctNo,
                                    case
                                        when u.origin='CAMT' then
                                            case
                                                when (u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic) or
                                                     (u.payeeAccountNumber=k.iban and substr(u.payeeBankcode||'XXX',1,11)=k.bic) then
                                                    case
                                                        when u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic then
                                                            u.payeeBankcode
                                                        else
                                                            u.remitterBankcode
                                                        end
                                                else
                                                    null
                                                end
                                        else
                                            null
                                        end as RmtdAcctBIC,
                                    case
                                        when u.origin='CAMT' then
                                            case
                                                when (u.remitterAccountNumber=k.iban and substr(u.remitterBankcode||'XXX',1,11)=k.bic) or
                                                     (u.payeeAccountNumber=k.iban and substr(u.payeeBankcode||'XXX',1,11)=k.bic) then
                                                    null
                                                else
                                                    case
                                                        when u.remitterAccountNumber=k.kontoNummer and u.remitterBankcode=k.kontoBlz then
                                                            u.payeeBankcode
                                                        else
                                                            case
                                                                when u.payeeAccountNumber=k.kontoNummer and u.payeeBankcode=k.kontoBlz then
                                                                    u.remitterBankcode
                                                                else
                                                                    case
                                                                        when instr(u.betrag,'-')=1 then
                                                                            u.payeeBankcode
                                                                        else
                                                                            u.remitterBankcode
                                                                        end
                                                                end
                                                        end
                                                end
                                        else
                                            u.blz
                                        end as RmtdBankCode,
                                    null as Category,
                                    null as Notes,
                                    'BOOK' as BookgSts,
                                    u.umsatzart as GVC,
                                    case
                                        when u.textKeySuffix='000' then
                                            null
                                        else
                                            u.textKeySuffix
                                        end as GVCExtension
                                    from giro_umsatz as u
                                    left join konten as k on u.idKonto=k._id
                                    where k.iban like ?
                                    order by u.idKonto, u.buchungsDatum, u._id
                                    """, [args.account])
                sys.stdout.buffer.write('\t'.join(field[0] for field in cursor.description).encode('iso8859-1')+b'\n')
                for row in cursor:
                    sys.stdout.buffer.write('\t'.join(str(field) if field is not None else '' for field in row).encode('iso8859-1')+b'\n')
